### ISSUE TITLE
Concent VM: a single configuration file

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#278]
Currently setting up the virtual machine requires creating two configuration files (`extra_settings.py` and `signing-service-env.sh`) and a shell variable (`CONCENT_DEPLOYMENT_VERSION`). There will be more as we make the machine more versatile (e.g. `app_cfg.ini`) for Golem. The goal of this task is replace it all with a single configuration file.

1) The configuration file should be called `config.yml`.
    - It should not be stored in the repository (add to `.gitignore`).
    - If the file does not exist, `Vagrantfile` should exit with a clear error message.
2) `extra_settings.py` should now be created automatically inside the machine from a template and contain all settings from a dict called `concent_local_settings`.
3) `signing_service-env.sh` should now be created automatically inside the machine from a template and contain all shell variables from a dict called `signing_service_env`.
4) `CONCENT_DEPLOYMENT_VERSION` should be replaced with a top-level variable called `concent_deployment_version`. The playbooks can read it directly from `config.yml` instead of expecting Vagrant to pass it to them.

#### `config.yml`
``` yaml
concent_deployment_version: dev

concent_local_settings:
    USE_SIGNING_SERVICE:          true
    ADDITIONAL_VERIFICATION_COST: 1
    MIDDLEMAN_ADDRESS:            middleman.default.svc.cluster.local
    MIDDLEMAN_PORT:               9054

signing_service_env:
    ETHEREUM_PRIVATE_KEY:        "ZjIwODU2ZmFhN2YxOTQzN2E0MGIwODAxYjdlNDc1Y2U0ZWZhNTkzMmVkYmFhYmMyMjFiODQ5N2VlMGM1YzRiNSAgLQo="
    SIGNING_SERVICE_PRIVATE_KEY: "OTYyNmMxYzJhZmJlYzVjMmM5NGNlYmRjMzE4N2M5MjcgIC0K"
```

#### `extra_settings.py`
The generated file should contain only the following:
``` python
USE_SIGNING_SERVICE = True
ADDITIONAL_VERIFICATION_COST = 1
MIDDLEMAN_ADDRESS = 'middleman.default.svc.cluster.local'
MIDDLEMAN_PORT = 9054
```

#### `signing_service-env.sh`
The generated file should contain only the following:
``` bash
export ETHEREUM_PRIVATE_KEY="ZjIwODU2ZmFhN2YxOTQzN2E0MGIwODAxYjdlNDc1Y2U0ZWZhNTkzMmVkYmFhYmMyMjFiODQ5N2VlMGM1YzRiNSAgLQo="
export SIGNING_SERVICE_PRIVATE_KEY="OTYyNmMxYzJhZmJlYzVjMmM5NGNlYmRjMzE4N2M5MjcgIC0K"
```
