### ISSUE TITLE
Sometimes load balancer does not detach nginx-proxy from external ip

### ISSUE THREAD

**Issue by bartoszbetka** [golemfactory/concent-deployment#49]
When nginx-proxy deployment and service was deleted from cluster, sometimes load balancer not detach external IP from nginx-proxy service.

My theory is that maybe option describe below in nginx-proxy deployment causes that problem. 
```
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]
```
This option allows you to immediately close nginx before removing pod.
