### ISSUE TITLE
Single list of container and package versions

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#78]
We need a file where we could keep versions of base Docker images, images used in Kubernetes configs, linux packages and anything else that's hard-coded in the deployment repo. We want versions hard-coded to avoid situations where the version can change during deployment but we need to do it in a way that does not make it hard to find and update those versions regularly.

Things to do:
- Create `containers/versions.yml`. Define versions in it, like this:
    ``` yaml
    debian_version:   "9.4"
    postgres_version: "10.3-alpine"
    nginx_version:    "1.13.9-alpine"
    python_version:   "3.6"
    ```
- Include this file as one of the context files when rendering templates. Use these variables in `Dockerfile`s and scripts.
- Versions used in Ansible scripts for the build server should be there too. Python version, docker version, etc. You can add the version file as any other file with variables.
- Add versions in `Dockerfiles` and scripts that do not have versions hard-coded now.
    - You can also update everything else to the latest version (but in a separate commit).
- Put any versions used in Kubernetes configs in `versions.yml` too. Then include this file as context when building Kubernetes scripts.

Things to consider
- It might be also a good idea to extract whole package lists from scripts into `versions.yml`.
